name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Statische Seite bauen
        run: |
          # Beispiel: Erstelle den Ordner "public" und eine einfache index.html
          mkdir -p public
          echo "<!DOCTYPE html><html><head><meta charset='utf-8'><title>Meine Seite</title></head><body><h1>Hallo Welt</h1></body></html>" > public/index.html

      - name: Zu GitHub Pages deployen
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
